# Generated by Django 3.1.7 on 2021-03-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='timestamp_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='timestamp_out',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
