# Generated by Django 3.1.7 on 2021-04-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0003_auto_20210323_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp_in', models.DateTimeField(auto_now_add=True)),
                ('timestamp_out', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=140)),
            ],
        ),
        migrations.DeleteModel(
            name='visitas',
        ),
    ]
